# The 45 approved glossary terms (Kyle: "All").
# id -> (display term, expansion, [match patterns], case_sensitive)
TERMS = [
 ("deceptive-grounding", "deceptive grounding",
  "A retrieval failure where an answer about one thing is filled with a different thing's evidence and presented as the first thing's — while every statement still appears in the fetched documents, so the standard checks pass.",
  ["deceptive grounding"], False),
 ("dg", "DG",
  "Shorthand for deceptive grounding: answering about X using Y's evidence without ever saying so.",
  ["DG"], True),
 ("dg-y", "DG-Y",
  "The specific rate this study estimates — the share of trials whose answer used the sibling library Y's strings and never named Y.",
  ["DG-Y"], True),
 ("dg-any", "DG-any",
  "A contamination check: answers that pulled in strings from a third document, belonging to neither the queried thing nor its sibling.",
  ["DG-any"], True),
 ("rag", "retrieval-augmented generation (RAG)",
  "A setup where a system first fetches documents and then writes its answer from them, rather than from memory alone.",
  ["retrieval-augmented generation", "RAG"], True),
 ("grounding", "grounding",
  "Basing an answer on the fetched documents rather than on what the model already knows.",
  ["grounding"], False),
 ("faithfulness", "faithfulness",
  "Whether every claim in an answer is backed by some fetched document. Says nothing about whose evidence it is.",
  ["faithfulness"], False),
 ("citation-proxy", "citation proxy",
  "A mechanical check that the answer cites something, that every cited document was really fetched, and that every string appears in a cited one.",
  ["citation proxy"], False),
 ("identifier-shaped", "identifier-shaped / token-shaped strings",
  "Strings built to look like code identifiers — method names, config flags, error codes, version numbers — which is what makes them findable by pattern-matching.",
  ["identifier-shaped", "token-shaped"], False),
 ("confabulation", "confabulation",
  "Content in an answer that appears in no fetched document at all: invented rather than copied.",
  ["confabulation"], False),
 ("discriminated", "discriminated",
  "The label for an answer that used the other thing's evidence but named it, so a reader could tell. Deliberately not counted as DG.",
  ["discriminated"], False),
 ("misattributed-other", "misattributed-other",
  "The label for an answer containing strings that came from a fetched document but belong to neither the queried thing nor its sibling.",
  ["misattributed-other"], False),
 ("correct-refusal", "correct-refusal",
  "The label for an answer that declines because the documents don't cover the question — the desired behaviour when the evidence is missing.",
  ["correct-refusal"], False),
 ("engagement", "engagement",
  "The share of trials where the model actually tried to answer from the evidence instead of refusing.",
  ["engagement"], False),
 ("clean-trial", "clean trial",
  "A trial that produced a usable, scorable answer: no API error, no unparseable output, nothing vague.",
  ["clean trials", "clean trial"], False),
 ("wilson", "Wilson score interval",
  "A way of putting a margin-of-error range around a proportion that stays sensible even when the count is zero or very small.",
  ["Wilson score interval", "Wilson"], True),
 ("newcombe", "Newcombe interval",
  "A margin-of-error range around the difference between two proportions, built by combining each one's own range.",
  ["Newcombe interval", "Newcombe"], True),
 ("floor", "floor",
  "A number known to sit at or below the true value, so the truth can only be higher. Not an estimate of the value itself.",
  ["floors", "floor"], False),
 ("bound", "lower bound / upper bound",
  "The bottom and top ends of a margin-of-error range. A lower bound above zero means the thing happens at all.",
  ["lower bounds", "lower bound", "upper bounds", "upper bound"], False),
 ("pre-registration", "pre-registration / pre-registered",
  "Writing down the sample size, conditions, analysis and exact reporting wording before collecting data, so the analysis can't be tuned to the result.",
  ["pre-registration", "pre-registered"], False),
 ("power", "power",
  "How reliably a study could detect an effect of a given size if that effect were real — independent of what it actually observed.",
  ["power"], False),
 ("underpowered", "underpowered",
  "Having too few trials to detect the effect being looked for, so a “nothing found” result is uninformative.",
  ["underpowered"], False),
 ("null-verdict", "NULL",
  "A verdict of “no effect detected.” Not the same as showing there is no effect.",
  ["NULL"], True),
 ("precision-recall", "precision / recall",
  "Of a detector: what share of what it flagged was real, and what share of the real cases it caught.",
  ["precision", "recall"], False),
 ("temperature", "temperature",
  "A setting controlling how random a model's output is; zero is meant to make it give the same answer to the same prompt.",
  ["temperature"], False),
 ("deterministic", "deterministic",
  "Producing exactly the same output every time from the same starting point.",
  ["deterministically", "deterministic"], False),
 ("seed", "seed",
  "A fixed starting number for a random-number generator, so a “random” process regenerates identically on every run.",
  ["seeded", "seed"], False),
 ("cx-cy", "Cx / Cy",
  "The two axes of the design: how much of the queried thing's own evidence is present (Cx), and which document about the alternate thing is present (Cy).",
  ["Cx", "Cy"], True),
 ("null-control", "null_control",
  "The control setting whose alternate document contains no identifier strings at all, making the failure impossible there by construction.",
  ["null_control"], True),
 ("completing", "completing",
  "A document about the alternate thing that answers the exact shape of the question asked about the queried thing.",
  ["completing"], False),
 ("prior-completing", "prior_completing",
  "The original paper's condition where the alternate evidence is chosen to match what the model already believes about the queried thing.",
  ["prior_completing"], True),
 ("synthetic-y", "synthetic_Y",
  "The original paper's condition where the alternate thing's name is invented while its evidence is left unchanged.",
  ["synthetic_Y"], True),
 ("absent", "absent",
  "The setting where the queried thing's own documentation is withheld, so no correct answer exists in the fetched documents.",
  ["absent"], False),
 ("stark", "stark",
  "This study's plain presentation: prose documents, each titled with the name of the thing it describes, and a single alternate document.",
  ["stark"], False),
 ("camouflaged", "camouflaged",
  "This study's disguised presentation: JSON tool-results, one identical title on every document, plus four off-topic filler documents.",
  ["camouflaged", "camouflage"], False),
 ("surface", "surface",
  "A way of presenting the fetched documents to the model, treated here as an experimental factor in its own right.",
  ["surfaces", "surface"], False),
 ("filler", "filler",
  "An off-topic document added to a trial to make retrieval look realistic and to test whether the model grabs evidence indiscriminately.",
  ["fillers", "filler"], False),
 ("blinding", "blinding",
  "Keeping the outcome hidden while decisions are being made, so no choice about the run can be swayed by the result.",
  ["blinding"], False),
 ("schema", "schema",
  "The format in which fetched documents are handed to the model. Rates are not directly comparable across different formats.",
  ["schemas", "schema"], False),
 ("rag4", "RAG-4 / 10-tool",
  "Two document formats used in the original paper. This study ran neither of them.",
  ["RAG-4", "10-tool"], True),
 ("calibration-model", "calibration model",
  "The one model the original paper's materials were tuned to, which is why its numbers behave differently from every other model's.",
  ["calibration model"], False),
 ("reference-magnitude", "reference magnitude",
  "A number borrowed only to size the run and pick wording — not a hypothesis being tested.",
  ["reference magnitude"], False),
 ("point-estimate", "point estimate",
  "A single number quoted as the answer, with no range around it.",
  ["point estimate"], False),
 ("p-value", "p-value",
  "A single number summarising how surprising a result would be under some assumption. This study attaches none to any comparison.",
  ["p-values", "p-value"], False),
 ("run-hygiene", "dry run / smoke test / top-up",
  "Three cheap safety steps: running the scoring pipeline against fake answers before spending money; a handful of real calls before a full wave; and extra trials to replace unusable ones.",
  ["dry runs", "dry run", "smoke tests", "smoke test", "top-up"], False),
]

# Narrow, stated carve-out: "absent from" is ordinary English (an absent name),
# not the experimental condition, so that occurrence must not take the gloss.
NEGATIVE_LOOKAHEAD = {"absent": r"(?!\s+from)"}
